### ISSUE TITLE
Route

### ISSUE THREAD

**Issue by sarahyjja** [fac-17/Where-Should-We-Meet#15]
Same as the calendar  issue #13 
Can we add logos or link on a word when they choose they route?
<img width="400" alt="Capture d’écran 2019-09-09 à 10 50 25" src="https://user-images.githubusercontent.com/44409053/64521297-a8a65300-d2ef-11e9-90b4-cb125e65e67f.png">

**Comment by LaLeonie** [comment]
If we're linking the user to google or citymapper anyway, I think it would make sense to do that before we even show the route. They'll see different routes in those apps anyways, so it's redundant in our app. 

Instead of the route options, we could just have these buttons on our last page: 
- Link to Citymapper
- Link to Google Maps 
- Link to create calendar event 
- (Link to book a table at the venue)
